pipeline {
     agent any
     tools {nodejs "nodejs"}

     stages {
        stage("Build") {
            steps {
                dir("test") {
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Deploy") {
            steps {
                sh "sudo cp -r ${WORKSPACE}/build /home/build"
            }
        }
    }
}