pipeline {
     agent any
     tools {nodejs "nodejs"}

     stages {
        stage("Build") {
            steps {
                dir("test") {
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Deploy") {
            steps {
                dir("test") {
                    sh "pwd"
                    sh "ls"
                    sh "cp -r build /home/app/react/"
                }
            }
        }
    }
}
